theforeman/puppet-dhcp

spec/defines/pool_spec.rb
templates/dhcpd.pool.erb

When a user would pass an empty range parameter, it would result into
```
pool
{
range ;
}
```
dhcpd would fail to start after that. With this patch, the whole pool
block is omitted.
Closes GH-29

Allow empty range parameter

---

manifests/pool.pp

In 142c1fd3357e256b2437f6c6e60b8e2f55dca8a5 the use of the $dhcp_dir parameter was removed but not the code itself.

Remove unused code

---

manifests/host.pp

Since 142c1fd3357e256b2437f6c6e60b8e2f55dca8a5 the $dhcp_dir variable is unused.

Clean up host

---

spec/defines/pool_spec.rb
templates/dhcpd.pool.erb

Domain names were missing quotes, effectively failing dhcp to start with error on parsing config file. This is a fix.

Added quotes to domain name

---

manifests/init.pp
spec/classes/init_spec.rb
templates/dhcpd.conf.erb

This is needed so that the puppet-foreman_proxy module will be able to set up OMAPI in the dhcp server when the foreman-installer is called with the dhcp-key-name and dhcp-key-secret options.

Add support for setting up OMAPI key

---

manifests/init.pp
spec/classes/init_spec.rb
templates/dhcpd.conf.erb

ddns-domainname is needed when multiple domains set for a zone
ddns-rev-domainname is needed to support reverse lookup update

Add ddns-domainname and ddns-rev-domainname option

---

spec/defines/pool_spec.rb
templates/dhcpd.pool.erb

This fixes the syntax error that is described in #70. I also added a test for the string variant of the parameter.

fix dhcp domain-search syntax and add test

---

templates/dhcpd.pool.erb

This fixes #74 to allow proper naming within tools like webmin to display the pool name instead of `#################################`

Remove unnecessary hash-signes from pool config

---

manifests/params.pp
metadata.json
spec/classes/init_spec.rb

Tested on my DHCP proxy, seems to work.
One caveat is that you can't set the listen interfaces on Arch. There's no config file to alter, you're expected to set ranges or write a different systemd unit - https://wiki.archlinux.org/index.php/Dhcpd#Listening_on_only_one_interface has the details.
This doesn't cause me any issues, and users can always write a systemd unit elsewhere in their catalog and then override the value of `servicename` - so maybe it just needs documenting somewhere?

Add Archlinux support

---

README.md
spec/defines/pool_spec.rb
templates/dhcpd.pool.erb

* Subsequent definitions of of `{rfc3442,ms}-classless-static-routes` override their predecessors.  Perhaps this was not true in older versions of `dhcpd`, although I doubt it.
* There is no ability to define a `/0` masked static route.  With `dhcpcd` and perhaps other DHCP clients, option 3 (router) is ignored when `rfc3442-classless-static-routes` is specified, meaning there is no non-hackish way to specify a default route.
Yes, but only with Puppet 4.x and Debian family systems.
I've chosen a styling that I think appropriately balances readability of the template with readability of the resulting config.  There may be a better way to do this, I'm not that familiar with Ruby.  I am happy to make changes to better balance the two as per your preferences.

Fix classless static routes

---

manifests/pool.pp
spec/defines/pool_spec.rb
templates/dhcpd.pool.erb

This adds the possibility to override the filename for pxe booting per pool.
The filename is not an option, so use of $options is not possible. While $raw_append could be used to achieve the same goal, it's nice to have a separate argument for it. This also mirrors the argument list for init.pp more closely.

Add support for pxefilename for pools.

---

manifests/init.pp
spec/classes/init_spec.rb
templates/dhcpd.conf.erb

Defaults to maintaining existing behaviour (bootp enabled). Also cleanly applies to the 3.2-stable branch as of the time of this PR.

Allow turning bootp off

---

manifests/init.pp
spec/classes/init_spec.rb
templates/dhcpd.conf.erb
templates/dhcpd.conf.failover.erb

Moves dynamic includes *after* the failover configuration. BOOTP now defaults to off if failover is on and vice-versa. BOOTP can be explicitly set true or false regardless of failover, though. This enables safer default operation as defined in https://www.google.com/search?q=rfc+DHCP+Failover+Protocol.
This incorporates #97 as well.

Failover improvements

---

types/macaddress.pp

MAC addresses include the letter f and ISC DHCPd allows uppercase letters.

Correct MAC address definition

---

manifests/init.pp
templates/dhcpd.conf.erb

By defaulting to undef the current behaviour is maintained.
Closes GH-88

Allow choosing the DNS update server

---

.fixtures.yml
manifests/init.pp
metadata.json
spec/classes/failover_spec.rb
spec/classes/init_spec.rb
templates/redhat/systemd-dropin.conf.erb

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-dhcp-configuring-server.html#starting-stopping-server suggests to override the full file but this just uses a drop-in to change as little as possible.

Fixes #20912 - Listen on interfaces in EL7

---

templates/redhat/systemd-dropin.conf.erb

By using interfaces we broke support for the $interface parameter.
Closes GH-122

Use dhcp_interfaces in the systemd drop

---

manifests/init.pp
spec/classes/init_spec.rb
templates/dhcpd.conf.erb

This allows the installer to set a specific warning that's tailored to the installer. It won't affect users outside of the installer. It also allows changing the message in a downstream product to include help URLs.
Alternative to https://github.com/theforeman/puppet-dhcp/pull/148

Make the config header configurable

---

manifests/init.pp
spec/classes/init_spec.rb
templates/dhcpd.conf.erb

This commit allow to provide a specific PXE filename when PXE client is
iPXE compliant.
Note: This, consequently, allow to fetch directly boot files through
HTTP.
Source: https://projects.theforeman.org/projects/foreman/wiki/Fetch_boot_files_via_http_instead_of_TFTP

Support iPXE without chain-loading

---

manifests/failover.pp

I was able to run spec tests once again after making the change locally. Testing now if it will work on Travis as well.

document failover parameters

---

manifests/init.pp
manifests/params.pp

We should not change the system defaults for config directory mode, if not asked by user.
We can although manage a group owner of the directory if asked to do so by user.
We at the same time don't need to manage a directory if it's not dhcp specific.

Adjust config directory mode to the system defaults

---

manifests/params.pp

In d237525bad20e7267a37d8792a52b4af5aece4f1 we have falsely introduced 0750 as default for Debian.

Fix default conf_dir mode for Debian

---

manifests/init.pp
spec/classes/init_spec.rb
templates/dhcpd.conf.erb

when using the *interim* update style for DDNS, clients can choose
to update their own A record. this options instructs the server
to ignore that request and update both the PTR and A records.

add support for client-updates instruction for interim DDNS.

---

metadata.json

The breaking changes do not affect this module and allows Puppet 7 compatibility.

Mark compatible with camptocamp/systemd 3

---

spec/classes/failover_spec.rb
spec/classes/init_spec.rb
spec/defines/class_spec.rb
spec/defines/host_spec.rb
spec/defines/pool_spec.rb

Per discussion in #193, these helper methods should be removed.  Care was taken not to obscure the odd whitespace in several of the ERB templates by matching with regular expressions, in case it is desirable to cleanup the templates in the future.

remove unnecessary usage of concat spec helper methods

---

manifests/init.pp

By using notify_service we ensure that the drop-in exists before the service is started and restarted if it changes.

Ensure systemd drop-in happens before service

---

metadata.json
templates/debian/default_isc-dhcp-server

The primary motivation was to update the /etc/default-isc-dhcp-server file to the new template introduced in Debian 9. Debian 8 is EOL so there's no point in trying to support the old format.

Drop Debian 8 support and update default template

---

.fixtures.yml

The setting isn't required anymore since the module supports puppet 6.15
and newer.

.fixtures.yml: Cleanup puppet_version

---

manifests/host.pp
spec/defines/host_spec.rb
templates/dhcpd.host.erb

similar to the main config and subnet sections, this 
change adds support for appending/prepending raw
DHCPd configuration fragments to host sections.

add support for raw configuration for host declarations.

---

templates/dhcpd.subnet.erb

I tried to configure the nameserver with a example IP of 10.1.1.1 as my first priority nameserver in one of my configured DHCP pools.
```
nameservers:
- '10.1.1.1'
- '1.2.3.4'
- '1.2.3.5'
```
But this nameserver was always landed as the last priority nameserver in /etc/dhcp/dhcpd.conf.
```
option domain-name-servers 1.2.3.4, 1.2.3.5, 10.1.1.1;
```
That's why I would suggest to remove the sort function for the nameservers array in the "dhcpd.subnet.erb" template.

Remove nameserver sorting for dhcp subnet configurations

---

manifests/params.pp

* the files with the path grub2/bootx64.efi do not exist on a ubuntu 20.04 installation with foreman 3.6.0
* during the foreman_proxy netboot setup, symlinks for the grub2 pxe efi files with the name grub2/shim.efi are created here https://github.com/theforeman/puppet-foreman_proxy/blob/1a42903ead90fa9622ac123511e5b5f9eece8f79/manifests/tftp/netboot.pp#L56-L76
* this change aligns the dhcpd bootfile path with the settings already used for RedHat distributions by also using the symlink created and fixes the current issue of non existent files with the name grub2/bootx64.efi

debian grub2: update efi file name to align with symlink name

---

metadata.json
spec/acceptance/basic_spec.rb
spec/acceptance/nameservers_spec.rb

Right now this is mostly to see how CI deals with it.

Add Puppet 8 support

---

metadata.json
spec/setup_acceptance_node.pp

Added AlmaLinux 8 and 9 to the supported operating systems in metadata.json.
These changes ensure that we start testing with AlmaLinux 8 and 9 instead of CentOS 8 Stream. This update is part of our transition to better support AlmaLinux in our Puppet modules.
See, for details: https://github.com/theforeman/foreman-infra/issues/2087

Add AlmaLinux 8 & 9 support
